set_property SRC_FILE_INFO {cfile:C:/Users/tahir/Desktop/Xilinx_Counter_for_Arty_S7_25/tt.xdc rfile:../../../../../tt.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVTTL [get_ports {counter_out[3]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVTTL [get_ports {counter_out[2]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVTTL [get_ports {counter_out[1]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVTTL [get_ports {counter_out[0]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVTTL [get_ports clk]
